spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Develop/Study/StudyList/h2/testcase
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #global하게 설정
#    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace